version: '3.8'
x-db-config:
  &db-config
  MYSQL_USER: forge
  MYSQL_PASSWORD: pass1234
  MYSQL_DATABASE: forge
services:
  php-apache-environment:
    container_name: php-apache
    build:
        context: ./docker/php
        dockerfile: Dockerfile
    depends_on:
        - db
    image: php:8.0-apache
    volumes:
      - ./src:/var/www/html
      - ./docker/php/init.sh:/app/init/init.sh
    ports:
      - 8000:80
    # command: bash -c "/app/init/init.sh"
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      << : *db-config
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_ROOT_HOST: '%'
    ports:
        - "9906:3306"
    volumes:
      - /sessions
  phpmyadmin:
    container_name: docker-laravel-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions
